### ISSUE TITLE
the cheat doesn't work

### ISSUE THREAD

**Issue by THMaST3R** [ConfusedCharacter/NotCoin-Cheat#2]
what is this problem?

```
Traceback (most recent call last):
  File "/root/NotCoin-Cheat/NotCoin.py", line 10, in <module>
    client = TelegramClient("cheat",123,"123").start()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 184, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 434, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)
Segmentation fault (core dumped)
```

**Comment by ConfusedCharacter** [comment]
you should put your api hash and api id from <my.telegram.org> here.

**Comment by Unknown-warior** [comment]
> you should put your api hash and api id from <my.telegram.org> here.

Where and how to your api hash and api id please?

**Comment by ConfusedCharacter** [comment]
login in to my.telegram.org , go to development part , fill all parts , telegram gives you api id and api hash at the end. otherwise google.com helps you
