### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tawanaproxy** [ConfusedCharacter/NotCoin-Cheat#5]
iget this erorre 

Traceback (most recent call last):
  File "/root/ton1/NotCoin-Cheat/NotCoin.py", line 97, in <module>
    hashes = send_result['data'][0]['hash']
TypeError: 'NoneType' object is not subscriptable
root@ubuntu-s-2vcpu-2gb-ams3-01:~/ton1/NotCoin-Cheat# python3 NotCoin.py
collect coins: 50 with hash 1
Traceback (most recent call last):
  File "/root/ton1/NotCoin-Cheat/NotCoin.py", line 97, in <module>
    hashes = send_result['data'][0]['hash']
TypeError: 'NoneType' object is not subscriptable

**Comment by ConfusedCharacter** [comment]
use latest source.
