### ISSUE TITLE
Error "Traceback (most recent call last)"

### ISSUE THREAD

**Issue by THMaST3R** [ConfusedCharacter/NotCoin-Cheat#6]
Hi there is a problem. my api id and api hash is correct

```
Traceback (most recent call last):
  File "/root/NotCoin-Cheat/NotCoin.py", line 10, in <module>
    client = TelegramClient("cheat",..........,"........").start()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/telegrambaseclient.py", line 555, in connect
    self.session.auth_key = self._sender.auth_key
  File "/usr/local/lib/python3.10/dist-packages/telethon/sessions/sqlite.py", line 180, in auth_key
    self._update_session_table()
  File "/usr/local/lib/python3.10/dist-packages/telethon/sessions/sqlite.py", line 194, in _update_session_table
    c.execute('delete from sessions')
sqlite3.OperationalError: database is locked
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /usr/local/lib/python3.10/dist-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /usr/local/lib/python3.10/dist-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /usr/local/lib/python3.10/dist-packages/telethon/network/connection/connection.py:316> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /usr/local/lib/python3.10/dist-packages/telethon/network/connection/connection.py:335> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object Connection._recv_loop at 0x7f4b43238ba0>
RuntimeError: coroutine ignored GeneratorExit
```

**Comment by ConfusedCharacter** [comment]
hi , your sql database locked it means you have running script more than 1, delete session and login again.
