### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MianajiAli** [ConfusedCharacter/NotCoin-Cheat#8]
![image](https://github.com/ConfusedCharacter/NotCoin-Cheat/assets/87234097/af35de0d-1da3-4808-8349-4dc88671c494)
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Traceback (most recent call last):
  File "/home/aria/github/notcoinpy/NotCoin.py", line 10, in <module>
    client = TelegramClient("cheat",123,"123").start()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aria/.local/lib/python3.11/site-packages/telethon/client/auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/aria/.local/lib/python3.11/site-packages/telethon/client/auth.py", line 135, in _start
    await self.connect()
  File "/home/aria/.local/lib/python3.11/site-packages/telethon/client/telegrambaseclient.py", line 544, in connect
    if not await self._sender.connect(self._connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aria/.local/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 134, in connect
    await self._connect()
  File "/home/aria/.local/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 260, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by ConfusedCharacter** [comment]
use VPN or proxy
